//! Static X API endpoint definitions — the spec pack.
//!
//! Each `EndpointDef` maps one X API v2 (or v1.1) endpoint to an MCP tool.
//! Only *new* endpoints are defined here — the 29 curated Layer 1 tools
//! already exist in `manifest.rs` and are not duplicated.

use crate::contract::error_code::ErrorCode;
use crate::tools::manifest::{Profile, ToolCategory};

use super::params::{EndpointDef, HttpMethod, ParamDef, ParamType};

// ── Profile shorthands ─────────────────────────────────────────────────

const ALL_FOUR: &[Profile] = &[
    Profile::Readonly,
    Profile::ApiReadonly,
    Profile::Write,
    Profile::Admin,
];
const WRITE_UP_AND_API_RO: &[Profile] = &[Profile::ApiReadonly, Profile::Write, Profile::Admin];
const WRITE_UP: &[Profile] = &[Profile::Write, Profile::Admin];

// ── Error code sets ────────────────────────────────────────────────────

const X_READ_ERR: &[ErrorCode] = &[
    ErrorCode::XNotConfigured,
    ErrorCode::XRateLimited,
    ErrorCode::XAuthExpired,
    ErrorCode::XForbidden,
    ErrorCode::XNetworkError,
    ErrorCode::XApiError,
];

const X_WRITE_ERR: &[ErrorCode] = &[
    ErrorCode::XNotConfigured,
    ErrorCode::XRateLimited,
    ErrorCode::XAuthExpired,
    ErrorCode::XForbidden,
    ErrorCode::XNetworkError,
    ErrorCode::XApiError,
    ErrorCode::ScraperMutationBlocked,
    ErrorCode::PolicyDeniedBlocked,
    ErrorCode::PolicyDeniedRateLimited,
    ErrorCode::PolicyDeniedHardRule,
    ErrorCode::PolicyDeniedUserRule,
    ErrorCode::PolicyError,
];

// ── Common parameter definitions ───────────────────────────────────────

const PARAM_ID: ParamDef = ParamDef {
    name: "id",
    param_type: ParamType::String,
    required: true,
    description: "Resource ID",
    default: None,
};

const PARAM_USER_ID: ParamDef = ParamDef {
    name: "user_id",
    param_type: ParamType::String,
    required: true,
    description: "User ID (authenticated user for /me endpoints)",
    default: None,
};

const PARAM_TARGET_USER_ID: ParamDef = ParamDef {
    name: "target_user_id",
    param_type: ParamType::String,
    required: true,
    description: "Target user ID",
    default: None,
};

const PARAM_MAX_RESULTS: ParamDef = ParamDef {
    name: "max_results",
    param_type: ParamType::Integer,
    required: false,
    description: "Maximum number of results to return",
    default: Some("100"),
};

const PARAM_PAGINATION_TOKEN: ParamDef = ParamDef {
    name: "pagination_token",
    param_type: ParamType::String,
    required: false,
    description: "Token for paginating through results",
    default: None,
};

const PARAM_TWEET_FIELDS: ParamDef = ParamDef {
    name: "tweet_fields",
    param_type: ParamType::StringArray,
    required: false,
    description: "Comma-separated tweet fields to include (e.g. created_at,public_metrics)",
    default: None,
};

const PARAM_USER_FIELDS: ParamDef = ParamDef {
    name: "user_fields",
    param_type: ParamType::StringArray,
    required: false,
    description: "Comma-separated user fields to include (e.g. created_at,public_metrics)",
    default: None,
};

const PARAM_EXPANSIONS: ParamDef = ParamDef {
    name: "expansions",
    param_type: ParamType::StringArray,
    required: false,
    description: "Comma-separated expansions (e.g. author_id,referenced_tweets.id)",
    default: None,
};

const PARAM_LIST_FIELDS: ParamDef = ParamDef {
    name: "list_fields",
    param_type: ParamType::StringArray,
    required: false,
    description: "Comma-separated list fields (e.g. created_at,member_count,owner_id)",
    default: None,
};

const PARAM_SPACE_FIELDS: ParamDef = ParamDef {
    name: "space_fields",
    param_type: ParamType::StringArray,
    required: false,
    description: "Comma-separated space fields (e.g. host_ids,title,state)",
    default: None,
};

// ── The spec pack ──────────────────────────────────────────────────────

/// All X API endpoint definitions in the spec pack.
///
/// Sorted alphabetically by `tool_name` for deterministic output.
/// Only new endpoints — existing curated tools are not duplicated.
pub static SPEC_ENDPOINTS: &[EndpointDef] = &[
    // ── Batch Lookups (3) ──────────────────────────────────────────
    EndpointDef {
        tool_name: "x_v2_tweets_lookup",
        description: "Look up multiple tweets by their IDs in a single request",
        method: HttpMethod::Get,
        path: "/2/tweets",
        category: ToolCategory::Read,
        profiles: ALL_FOUR,
        scopes: &["tweet.read", "users.read"],
        params: &[
            ParamDef {
                name: "ids",
                param_type: ParamType::StringArray,
                required: true,
                description: "Comma-separated tweet IDs (up to 100)",
                default: None,
            },
            PARAM_TWEET_FIELDS,
            PARAM_USER_FIELDS,
            PARAM_EXPANSIONS,
        ],
        error_codes: X_READ_ERR,
        api_version: "v2",
        group: "tweets",
    },
    EndpointDef {
        tool_name: "x_v2_users_lookup_by_usernames",
        description: "Look up multiple users by their usernames in a single request",
        method: HttpMethod::Get,
        path: "/2/users/by",
        category: ToolCategory::Read,
        profiles: ALL_FOUR,
        scopes: &["users.read"],
        params: &[
            ParamDef {
                name: "usernames",
                param_type: ParamType::StringArray,
                required: true,
                description: "Comma-separated usernames (up to 100, without @ prefix)",
                default: None,
            },
            PARAM_USER_FIELDS,
            PARAM_EXPANSIONS,
        ],
        error_codes: X_READ_ERR,
        api_version: "v2",
        group: "users",
    },
    EndpointDef {
        tool_name: "x_v2_tweets_retweeted_by",
        description: "Get users who retweeted a specific tweet",
        method: HttpMethod::Get,
        path: "/2/tweets/{id}/retweeted_by",
        category: ToolCategory::Read,
        profiles: ALL_FOUR,
        scopes: &["tweet.read", "users.read"],
        params: &[
            PARAM_ID,
            PARAM_MAX_RESULTS,
            PARAM_PAGINATION_TOKEN,
            PARAM_USER_FIELDS,
        ],
        error_codes: X_READ_ERR,
        api_version: "v2",
        group: "tweets",
    },
    // ── Tweet Metadata (4) ─────────────────────────────────────────
    EndpointDef {
        tool_name: "x_v2_tweets_quote_tweets",
        description: "Get tweets that quote a specific tweet",
        method: HttpMethod::Get,
        path: "/2/tweets/{id}/quote_tweets",
        category: ToolCategory::Read,
        profiles: ALL_FOUR,
        scopes: &["tweet.read", "users.read"],
        params: &[
            PARAM_ID,
            PARAM_MAX_RESULTS,
            PARAM_PAGINATION_TOKEN,
            PARAM_TWEET_FIELDS,
            PARAM_USER_FIELDS,
            PARAM_EXPANSIONS,
        ],
        error_codes: X_READ_ERR,
        api_version: "v2",
        group: "tweets",
    },
    EndpointDef {
        tool_name: "x_v2_tweets_counts_recent",
        description: "Get count of tweets matching a query from the last 7 days",
        method: HttpMethod::Get,
        path: "/2/tweets/counts/recent",
        category: ToolCategory::Read,
        profiles: WRITE_UP_AND_API_RO,
        scopes: &["tweet.read"],
        params: &[
            ParamDef {
                name: "query",
                param_type: ParamType::String,
                required: true,
                description: "Search query (same syntax as search/recent)",
                default: None,
            },
            ParamDef {
                name: "granularity",
                param_type: ParamType::String,
                required: false,
                description: "Aggregation granularity: minute, hour, or day",
                default: Some("hour"),
            },
            ParamDef {
                name: "start_time",
                param_type: ParamType::String,
                required: false,
                description: "Start time in ISO 8601 format",
                default: None,
            },
            ParamDef {
                name: "end_time",
                param_type: ParamType::String,
                required: false,
                description: "End time in ISO 8601 format",
                default: None,
            },
        ],
        error_codes: X_READ_ERR,
        api_version: "v2",
        group: "tweets",
    },
    EndpointDef {
        tool_name: "x_v2_tweets_hide_reply",
        description: "Hide a reply to one of your tweets",
        method: HttpMethod::Put,
        path: "/2/tweets/{id}/hidden",
        category: ToolCategory::Moderation,
        profiles: WRITE_UP,
        scopes: &["tweet.read", "tweet.moderate.write"],
        params: &[
            PARAM_ID,
            ParamDef {
                name: "hidden",
                param_type: ParamType::Boolean,
                required: true,
                description: "Set to true to hide, false to unhide",
                default: None,
            },
        ],
        error_codes: X_WRITE_ERR,
        api_version: "v2",
        group: "tweets",
    },
    EndpointDef {
        tool_name: "x_v2_tweets_unhide_reply",
        description: "Unhide a previously hidden reply",
        method: HttpMethod::Put,
        path: "/2/tweets/{id}/hidden",
        category: ToolCategory::Moderation,
        profiles: WRITE_UP,
        scopes: &["tweet.read", "tweet.moderate.write"],
        params: &[
            PARAM_ID,
            ParamDef {
                name: "hidden",
                param_type: ParamType::Boolean,
                required: true,
                description: "Set to false to unhide",
                default: None,
            },
        ],
        error_codes: X_WRITE_ERR,
        api_version: "v2",
        group: "tweets",
    },
    // ── Pin Management (2) ─────────────────────────────────────────
    EndpointDef {
        tool_name: "x_v2_users_pin_tweet",
        description: "Pin a tweet to your profile",
        method: HttpMethod::Put,
        path: "/2/users/{user_id}/pinned_tweet",
        category: ToolCategory::Engage,
        profiles: WRITE_UP,
        scopes: &["tweet.read", "users.read", "tweet.write"],
        params: &[
            PARAM_USER_ID,
            ParamDef {
                name: "tweet_id",
                param_type: ParamType::String,
                required: true,
                description: "ID of the tweet to pin",
                default: None,
            },
        ],
        error_codes: X_WRITE_ERR,
        api_version: "v2",
        group: "users",
    },
    EndpointDef {
        tool_name: "x_v2_users_unpin_tweet",
        description: "Unpin a tweet from your profile",
        method: HttpMethod::Delete,
        path: "/2/users/{user_id}/pinned_tweet",
        category: ToolCategory::Engage,
        profiles: WRITE_UP,
        scopes: &["tweet.read", "users.read", "tweet.write"],
        params: &[PARAM_USER_ID],
        error_codes: X_WRITE_ERR,
        api_version: "v2",
        group: "users",
    },
    // ── Lists (15) ─────────────────────────────────────────────────
    EndpointDef {
        tool_name: "x_v2_lists_get",
        description: "Look up a list by its ID",
        method: HttpMethod::Get,
        path: "/2/lists/{id}",
        category: ToolCategory::List,
        profiles: WRITE_UP_AND_API_RO,
        scopes: &["list.read"],
        params: &[PARAM_ID, PARAM_LIST_FIELDS, PARAM_EXPANSIONS],
        error_codes: X_READ_ERR,
        api_version: "v2",
        group: "lists",
    },
    EndpointDef {
        tool_name: "x_v2_lists_owned",
        description: "Get lists owned by a user",
        method: HttpMethod::Get,
        path: "/2/users/{user_id}/owned_lists",
        category: ToolCategory::List,
        profiles: WRITE_UP_AND_API_RO,
        scopes: &["list.read", "users.read"],
        params: &[
            PARAM_USER_ID,
            PARAM_MAX_RESULTS,
            PARAM_PAGINATION_TOKEN,
            PARAM_LIST_FIELDS,
        ],
        error_codes: X_READ_ERR,
        api_version: "v2",
        group: "lists",
    },
    EndpointDef {
        tool_name: "x_v2_lists_create",
        description: "Create a new list",
        method: HttpMethod::Post,
        path: "/2/lists",
        category: ToolCategory::List,
        profiles: WRITE_UP,
        scopes: &["list.write"],
        params: &[
            ParamDef {
                name: "name",
                param_type: ParamType::String,
                required: true,
                description: "Name of the list (max 25 characters)",
                default: None,
            },
            ParamDef {
                name: "description",
                param_type: ParamType::String,
                required: false,
                description: "Description of the list (max 100 characters)",
                default: None,
            },
            ParamDef {
                name: "private",
                param_type: ParamType::Boolean,
                required: false,
                description: "Whether the list is private",
                default: Some("false"),
            },
        ],
        error_codes: X_WRITE_ERR,
        api_version: "v2",
        group: "lists",
    },
    EndpointDef {
        tool_name: "x_v2_lists_update",
        description: "Update a list's name, description, or privacy setting",
        method: HttpMethod::Put,
        path: "/2/lists/{id}",
        category: ToolCategory::List,
        profiles: WRITE_UP,
        scopes: &["list.write"],
        params: &[
            PARAM_ID,
            ParamDef {
                name: "name",
                param_type: ParamType::String,
                required: false,
                description: "New name for the list",
                default: None,
            },
            ParamDef {
                name: "description",
                param_type: ParamType::String,
                required: false,
                description: "New description for the list",
                default: None,
            },
            ParamDef {
                name: "private",
                param_type: ParamType::Boolean,
                required: false,
                description: "Whether the list is private",
                default: None,
            },
        ],
        error_codes: X_WRITE_ERR,
        api_version: "v2",
        group: "lists",
    },
    EndpointDef {
        tool_name: "x_v2_lists_delete",
        description: "Delete a list you own",
        method: HttpMethod::Delete,
        path: "/2/lists/{id}",
        category: ToolCategory::List,
        profiles: WRITE_UP,
        scopes: &["list.write"],
        params: &[PARAM_ID],
        error_codes: X_WRITE_ERR,
        api_version: "v2",
        group: "lists",
    },
    EndpointDef {
        tool_name: "x_v2_lists_tweets",
        description: "Get tweets from a list's timeline",
        method: HttpMethod::Get,
        path: "/2/lists/{id}/tweets",
        category: ToolCategory::List,
        profiles: WRITE_UP_AND_API_RO,
        scopes: &["list.read", "tweet.read", "users.read"],
        params: &[
            PARAM_ID,
            PARAM_MAX_RESULTS,
            PARAM_PAGINATION_TOKEN,
            PARAM_TWEET_FIELDS,
            PARAM_USER_FIELDS,
            PARAM_EXPANSIONS,
        ],
        error_codes: X_READ_ERR,
        api_version: "v2",
        group: "lists",
    },
    EndpointDef {
        tool_name: "x_v2_lists_members",
        description: "Get members of a list",
        method: HttpMethod::Get,
        path: "/2/lists/{id}/members",
        category: ToolCategory::List,
        profiles: WRITE_UP_AND_API_RO,
        scopes: &["list.read", "users.read"],
        params: &[
            PARAM_ID,
            PARAM_MAX_RESULTS,
            PARAM_PAGINATION_TOKEN,
            PARAM_USER_FIELDS,
        ],
        error_codes: X_READ_ERR,
        api_version: "v2",
        group: "lists",
    },
    EndpointDef {
        tool_name: "x_v2_lists_members_add",
        description: "Add a user as a member of a list",
        method: HttpMethod::Post,
        path: "/2/lists/{id}/members",
        category: ToolCategory::List,
        profiles: WRITE_UP,
        scopes: &["list.write", "users.read"],
        params: &[
            PARAM_ID,
            ParamDef {
                name: "user_id",
                param_type: ParamType::String,
                required: true,
                description: "User ID to add to the list",
                default: None,
            },
        ],
        error_codes: X_WRITE_ERR,
        api_version: "v2",
        group: "lists",
    },
    EndpointDef {
        tool_name: "x_v2_lists_members_remove",
        description: "Remove a user from a list",
        method: HttpMethod::Delete,
        path: "/2/lists/{id}/members/{user_id}",
        category: ToolCategory::List,
        profiles: WRITE_UP,
        scopes: &["list.write", "users.read"],
        params: &[PARAM_ID, PARAM_TARGET_USER_ID],
        error_codes: X_WRITE_ERR,
        api_version: "v2",
        group: "lists",
    },
    EndpointDef {
        tool_name: "x_v2_lists_memberships",
        description: "Get lists a user is a member of",
        method: HttpMethod::Get,
        path: "/2/users/{user_id}/list_memberships",
        category: ToolCategory::List,
        profiles: WRITE_UP_AND_API_RO,
        scopes: &["list.read", "users.read"],
        params: &[
            PARAM_USER_ID,
            PARAM_MAX_RESULTS,
            PARAM_PAGINATION_TOKEN,
            PARAM_LIST_FIELDS,
        ],
        error_codes: X_READ_ERR,
        api_version: "v2",
        group: "lists",
    },
    EndpointDef {
        tool_name: "x_v2_lists_followers",
        description: "Get followers of a list",
        method: HttpMethod::Get,
        path: "/2/lists/{id}/followers",
        category: ToolCategory::List,
        profiles: WRITE_UP_AND_API_RO,
        scopes: &["list.read", "users.read"],
        params: &[
            PARAM_ID,
            PARAM_MAX_RESULTS,
            PARAM_PAGINATION_TOKEN,
            PARAM_USER_FIELDS,
        ],
        error_codes: X_READ_ERR,
        api_version: "v2",
        group: "lists",
    },
    EndpointDef {
        tool_name: "x_v2_lists_follow",
        description: "Follow a list",
        method: HttpMethod::Post,
        path: "/2/users/{user_id}/followed_lists",
        category: ToolCategory::List,
        profiles: WRITE_UP,
        scopes: &["list.write", "users.read"],
        params: &[
            PARAM_USER_ID,
            ParamDef {
                name: "list_id",
                param_type: ParamType::String,
                required: true,
                description: "ID of the list to follow",
                default: None,
            },
        ],
        error_codes: X_WRITE_ERR,
        api_version: "v2",
        group: "lists",
    },
    EndpointDef {
        tool_name: "x_v2_lists_unfollow",
        description: "Unfollow a list",
        method: HttpMethod::Delete,
        path: "/2/users/{user_id}/followed_lists/{list_id}",
        category: ToolCategory::List,
        profiles: WRITE_UP,
        scopes: &["list.write", "users.read"],
        params: &[
            PARAM_USER_ID,
            ParamDef {
                name: "list_id",
                param_type: ParamType::String,
                required: true,
                description: "ID of the list to unfollow",
                default: None,
            },
        ],
        error_codes: X_WRITE_ERR,
        api_version: "v2",
        group: "lists",
    },
    EndpointDef {
        tool_name: "x_v2_lists_pinned",
        description: "Get a user's pinned lists",
        method: HttpMethod::Get,
        path: "/2/users/{user_id}/pinned_lists",
        category: ToolCategory::List,
        profiles: WRITE_UP_AND_API_RO,
        scopes: &["list.read", "users.read"],
        params: &[PARAM_USER_ID, PARAM_LIST_FIELDS],
        error_codes: X_READ_ERR,
        api_version: "v2",
        group: "lists",
    },
    EndpointDef {
        tool_name: "x_v2_lists_pin",
        description: "Pin a list",
        method: HttpMethod::Post,
        path: "/2/users/{user_id}/pinned_lists",
        category: ToolCategory::List,
        profiles: WRITE_UP,
        scopes: &["list.write", "users.read"],
        params: &[
            PARAM_USER_ID,
            ParamDef {
                name: "list_id",
                param_type: ParamType::String,
                required: true,
                description: "ID of the list to pin",
                default: None,
            },
        ],
        error_codes: X_WRITE_ERR,
        api_version: "v2",
        group: "lists",
    },
    // ── Mutes (3) ──────────────────────────────────────────────────
    EndpointDef {
        tool_name: "x_v2_mutes_list",
        description: "Get users you have muted",
        method: HttpMethod::Get,
        path: "/2/users/{user_id}/muting",
        category: ToolCategory::Moderation,
        profiles: WRITE_UP_AND_API_RO,
        scopes: &["mute.read", "users.read"],
        params: &[
            PARAM_USER_ID,
            PARAM_MAX_RESULTS,
            PARAM_PAGINATION_TOKEN,
            PARAM_USER_FIELDS,
        ],
        error_codes: X_READ_ERR,
        api_version: "v2",
        group: "mutes",
    },
    EndpointDef {
        tool_name: "x_v2_mutes_create",
        description: "Mute a user",
        method: HttpMethod::Post,
        path: "/2/users/{user_id}/muting",
        category: ToolCategory::Moderation,
        profiles: WRITE_UP,
        scopes: &["mute.write", "users.read"],
        params: &[
            PARAM_USER_ID,
            ParamDef {
                name: "target_user_id",
                param_type: ParamType::String,
                required: true,
                description: "ID of the user to mute",
                default: None,
            },
        ],
        error_codes: X_WRITE_ERR,
        api_version: "v2",
        group: "mutes",
    },
    EndpointDef {
        tool_name: "x_v2_mutes_delete",
        description: "Unmute a user",
        method: HttpMethod::Delete,
        path: "/2/users/{user_id}/muting/{target_user_id}",
        category: ToolCategory::Moderation,
        profiles: WRITE_UP,
        scopes: &["mute.write", "users.read"],
        params: &[PARAM_USER_ID, PARAM_TARGET_USER_ID],
        error_codes: X_WRITE_ERR,
        api_version: "v2",
        group: "mutes",
    },
    // ── Blocks (3) ─────────────────────────────────────────────────
    EndpointDef {
        tool_name: "x_v2_blocks_list",
        description: "Get users you have blocked",
        method: HttpMethod::Get,
        path: "/2/users/{user_id}/blocking",
        category: ToolCategory::Moderation,
        profiles: WRITE_UP_AND_API_RO,
        scopes: &["block.read", "users.read"],
        params: &[
            PARAM_USER_ID,
            PARAM_MAX_RESULTS,
            PARAM_PAGINATION_TOKEN,
            PARAM_USER_FIELDS,
        ],
        error_codes: X_READ_ERR,
        api_version: "v2",
        group: "blocks",
    },
    EndpointDef {
        tool_name: "x_v2_blocks_create",
        description: "Block a user",
        method: HttpMethod::Post,
        path: "/2/users/{user_id}/blocking",
        category: ToolCategory::Moderation,
        profiles: WRITE_UP,
        scopes: &["block.write", "users.read"],
        params: &[
            PARAM_USER_ID,
            ParamDef {
                name: "target_user_id",
                param_type: ParamType::String,
                required: true,
                description: "ID of the user to block",
                default: None,
            },
        ],
        error_codes: X_WRITE_ERR,
        api_version: "v2",
        group: "blocks",
    },
    EndpointDef {
        tool_name: "x_v2_blocks_delete",
        description: "Unblock a user",
        method: HttpMethod::Delete,
        path: "/2/users/{user_id}/blocking/{target_user_id}",
        category: ToolCategory::Moderation,
        profiles: WRITE_UP,
        scopes: &["block.write", "users.read"],
        params: &[PARAM_USER_ID, PARAM_TARGET_USER_ID],
        error_codes: X_WRITE_ERR,
        api_version: "v2",
        group: "blocks",
    },
    // ── Spaces (6) ─────────────────────────────────────────────────
    EndpointDef {
        tool_name: "x_v2_spaces_get",
        description: "Look up a Space by its ID",
        method: HttpMethod::Get,
        path: "/2/spaces/{id}",
        category: ToolCategory::Read,
        profiles: WRITE_UP_AND_API_RO,
        scopes: &["space.read"],
        params: &[PARAM_ID, PARAM_SPACE_FIELDS, PARAM_EXPANSIONS],
        error_codes: X_READ_ERR,
        api_version: "v2",
        group: "spaces",
    },
    EndpointDef {
        tool_name: "x_v2_spaces_lookup",
        description: "Look up multiple Spaces by their IDs",
        method: HttpMethod::Get,
        path: "/2/spaces",
        category: ToolCategory::Read,
        profiles: WRITE_UP_AND_API_RO,
        scopes: &["space.read"],
        params: &[
            ParamDef {
                name: "ids",
                param_type: ParamType::StringArray,
                required: true,
                description: "Comma-separated Space IDs",
                default: None,
            },
            PARAM_SPACE_FIELDS,
            PARAM_EXPANSIONS,
        ],
        error_codes: X_READ_ERR,
        api_version: "v2",
        group: "spaces",
    },
    EndpointDef {
        tool_name: "x_v2_spaces_by_creator",
        description: "Get Spaces created by specific users",
        method: HttpMethod::Get,
        path: "/2/spaces/by/creator_ids",
        category: ToolCategory::Read,
        profiles: WRITE_UP_AND_API_RO,
        scopes: &["space.read", "users.read"],
        params: &[
            ParamDef {
                name: "user_ids",
                param_type: ParamType::StringArray,
                required: true,
                description: "Comma-separated user IDs of Space creators",
                default: None,
            },
            PARAM_SPACE_FIELDS,
            PARAM_EXPANSIONS,
        ],
        error_codes: X_READ_ERR,
        api_version: "v2",
        group: "spaces",
    },
    EndpointDef {
        tool_name: "x_v2_spaces_search",
        description: "Search for Spaces by title",
        method: HttpMethod::Get,
        path: "/2/spaces/search",
        category: ToolCategory::Read,
        profiles: WRITE_UP_AND_API_RO,
        scopes: &["space.read"],
        params: &[
            ParamDef {
                name: "query",
                param_type: ParamType::String,
                required: true,
                description: "Search query to find Spaces by title",
                default: None,
            },
            ParamDef {
                name: "state",
                param_type: ParamType::String,
                required: false,
                description: "Filter by state: live, scheduled, or all",
                default: Some("all"),
            },
            PARAM_SPACE_FIELDS,
            PARAM_EXPANSIONS,
        ],
        error_codes: X_READ_ERR,
        api_version: "v2",
        group: "spaces",
    },
    EndpointDef {
        tool_name: "x_v2_spaces_buyers",
        description: "Get users who purchased a ticket to a Space",
        method: HttpMethod::Get,
        path: "/2/spaces/{id}/buyers",
        category: ToolCategory::Read,
        profiles: WRITE_UP_AND_API_RO,
        scopes: &["space.read", "users.read"],
        params: &[PARAM_ID, PARAM_USER_FIELDS],
        error_codes: X_READ_ERR,
        api_version: "v2",
        group: "spaces",
    },
    EndpointDef {
        tool_name: "x_v2_spaces_tweets",
        description: "Get tweets shared in a Space",
        method: HttpMethod::Get,
        path: "/2/spaces/{id}/tweets",
        category: ToolCategory::Read,
        profiles: WRITE_UP_AND_API_RO,
        scopes: &["space.read", "tweet.read", "users.read"],
        params: &[
            PARAM_ID,
            PARAM_TWEET_FIELDS,
            PARAM_USER_FIELDS,
            PARAM_EXPANSIONS,
        ],
        error_codes: X_READ_ERR,
        api_version: "v2",
        group: "spaces",
    },
];
