#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
MARKER_PATH="$REPO_ROOT/crates/tuitbot-server/dashboard-release-marker.txt"

TMP_FILE="$(mktemp)"
cleanup() {
  rm -f "$TMP_FILE"
}
trap cleanup EXIT

python3 - "$REPO_ROOT" >"$TMP_FILE" <<'PY'
import hashlib
import pathlib
import subprocess
import sys

root = pathlib.Path(sys.argv[1])
paths = subprocess.check_output(
    ["git", "-C", str(root), "ls-files", "-z", "--", "dashboard/"]
)
items = [path.decode("utf-8") for path in paths.split(b"\0") if path]

digest = hashlib.sha256()
for rel in items:
    rel_bytes = rel.encode("utf-8")
    digest.update(rel_bytes)
    digest.update(b"\0")
    with open(root / rel, "rb") as handle:
        while True:
            chunk = handle.read(65536)
            if not chunk:
                break
            digest.update(chunk)
    digest.update(b"\0")

sys.stdout.write(
    "\n".join(
        [
            "# Auto-generated by scripts/update-dashboard-release-marker.sh.",
            "# Any tracked change under dashboard/ updates this file so release-plz",
            "# treats the dashboard bundle as a tuitbot-server package change.",
            f"dashboard_sha256={digest.hexdigest()}",
            f"tracked_files={len(items)}",
        ]
    )
    + "\n"
)
PY

mkdir -p "$(dirname "$MARKER_PATH")"
if [[ ! -f "$MARKER_PATH" ]] || ! cmp -s "$TMP_FILE" "$MARKER_PATH"; then
  mv "$TMP_FILE" "$MARKER_PATH"
  trap - EXIT
  echo "Updated $(realpath "$MARKER_PATH")"
else
  echo "$(realpath "$MARKER_PATH") is already up to date."
fi
